# Generated by Django 3.2.12 on 2022-05-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('sport_key', models.CharField(max_length=20)),
                ('commence_time', models.DateTimeField()),
                ('home_team', models.CharField(max_length=100)),
                ('home_team_odds', models.FloatField()),
                ('home_team_spread', models.FloatField()),
                ('home_team_ml', models.FloatField()),
                ('away_team', models.CharField(max_length=100)),
                ('away_team_odds', models.FloatField()),
                ('away_team_spread', models.FloatField()),
                ('away_team_ml', models.FloatField()),
            ],
        ),
    ]
