# Generated by Django 3.2.12 on 2022-05-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0002_auto_20220502_0250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team_ml',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team_odds',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_team_spread',
            field=models.CharField(max_length=20),
        ),
    ]
