# Generated by Django 3.2.12 on 2022-05-26 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0007_auto_20220526_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='bet_odds',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_status',
            field=models.CharField(default='disabled', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='bet_team_name',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
    ]
