# Generated by Django 3.2.12 on 2022-06-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0008_auto_20220526_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='game_status',
            field=models.CharField(default='Not Started', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_sccore',
            field=models.IntegerField(default=0),
        ),
    ]
