# Generated by Django 3.2.12 on 2022-06-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0009_auto_20220601_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='home_team_sccore',
            new_name='home_team_score',
        ),
    ]
