# Generated by Django 3.2.12 on 2022-07-14 04:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sportsbook', '0010_rename_home_team_sccore_game_home_team_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
